### ISSUE TITLE
Проверка

### ISSUE THREAD

**Issue by DenZhid** [Sanerins/auto-tests-2022#7]
Плюсы:
1. Инициализация логина и пароля для юзера через отдельный файл
1.5. Классные имена несуществующих друзей
2. Архитектура нормальная, но есть ряд замечаний
3. Почти все необходимые паттерны используются
4. Почти все фичи JUnit используются
5. Есть тест со стримом
6. Прикольная фича со статик методом openPage
7. Вынесены все SelenideElement'ы
8. Есть матчеры
9. Есть статические методы проверки чего то на экране, что делает тесты более читабильными

Минусы:
1. Нет паттернов: Page element
2. Нет JUnit: @Tag/@Disabled/@DisplayName, assertAll(), Таймауты для тестов
3. Паттерн билдер User'а очень примитивный
4. Кажется излишним в init() сперва открывать дефолтную страницу, а затем в каждом тесте вызывать authorize() и переходить снова на ok.ru
5. Можно isOpen проверять внутри самого пейджа в конструкторе и кидать исключение
6. Не совсем понятно зачем в searchPerson() в FriendPage вводить посимвольно и ждать 50 мс
7. Элементы не проверяются на shoudBe(visible) или подобное перед тем, как с ним взаимодействовать(вероятно, мы должны быть уверенным, что они уже отрисованы)
   Пример: У вас в коде: OPEN_POSTING_MENU_BTN.click();
		   Нужно: OPEN_POSTING_MENU_BTN.shouldBe(visible).click();
8. Condition можно импортировать статически для улучшения читаемости кода
9. В Page много повторяющихся методов, которые можно вынести в некий абстрактный класс и наследоваться от него и при необходимости переопределять его
10. Тесты простоваты.
11. Много где имеются неиспользуемые методы, которые стоит удалить, дабы не нагружать код.
12. IDEA подсвечивает методы openGuests(), openMessages(), openNotifications(), logout(), как те, которые можно преобразовать в void. Наверное их возвращаемые значения не используются.
13. Немного странно выглядит отрывание Page и их последующая проверка в GuestsOpeningTest, LoginTest и некоторых других функций от страниц.
Поясню:
	У вас: 
		authorize().openGuests();
        assertThat(GuestsPage.isOpen()).isTrue();
	Читаемее для меня было бы:
		GuestsPage guestPage = authorize().openGuests();
		assertThat(guestPage.isOpen).isTrue();
Скорее это вкусовщина, но к примеру в LikeTest такое хорошо используется у вас. 
P.S: В предложенном мной варианте тогда оправдывается, что методы из 13-го пункта возвращают Page.
14. Не нашёл в LikeTest снятия лайка после теста
15. Миксуются разные библиотеки: Selenium и Selenide (У Selenide есть свой метод byXpath, а у вас используется By.xpath()). Опять же не уверен, насколько это критично, но вроде бы говорилось, что нужно выбрать что-то одно.)
16. Unused protected static user field in BaseTest (warning IDEA)

Проверяли:
Задороцкас Никита
Жидков Денис
Бакин Даниил

Оценка: 6.5/10

**Comment by Sanerins** [comment]
Все пофикслили, по некоторым пунктам примечания:
3 - Кроме этого паттерна мы так же юзаем другой advanced петтерн - Data Provider, чтобы было более интереснее
5 - в конструкторах теперь применяем `shouldBe(VISIBLE)`, чтобы таким образом прерывать класс и элегантно сделать проверку одним ударом
6 - Ждать необходимо, чтобы эмулировать более натуральное поведение ввода, и чтобы он лучше работал(обсуждали это с учителем)
9 - удалили повторяющиеся методы, остались только повторяющиеся статические методы, а вынести их в отдельный класс - невозможно, т.к статические методы к классу напрямую и относятся
10 - добавили еще один сложный тест
